import type { Fingerprint } from '@opentechcheck/core'
import data from '../dist/fingerprints.json'

// Generated by `bun run compile` (packages/fingerprints/src/compile.ts).
// Run it once after checkout; CI runs it before typecheck/test/build.
export default data as Fingerprint[]
